import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./styles/index.scss";

const outfit = Outfit({
	subsets: ["latin"],
	variable: "--font-primary",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={outfit.variable}
			lang="en"
		>
			<body>{children}</body>
		</html>
	);
}
